### ISSUE TITLE
QA (#2959): Administration WorkflowSection loads without map TypeError

### ISSUE THREAD

**Issue by natechadwick-intsof** [intersoftdatalabs-in/percussioncms#2974]
## Parent
- Parent: #2959
- PR: https://github.com/intersoftdatalabs-in/percussioncms/pull/2973
- base_branch: main

## Summary
Verify that Admin → Administration loads the workflow administration shell without RouteErrorBoundary / `e.map is not a function` after the #2959 fix (unwrap Jackson `Workflow` metadata wrapper).

## Test plan
1. Deploy or run a CMS with PR #2973 WebUI (H2 QA docker or install).
2. Log in as **Admin**.
3. Open Admin (`?view=admin` or top nav Admin).
4. Click **Administration** sibling link (or navigate to `?view=workflow`).
5. Confirm `perc-workflow-admin-shell` and `perc-workflow-section` render.
6. Confirm workflow table or empty state appears; **Create Workflow** is visible.
7. Confirm browser console has **no** `TypeError: …map is not a function` and UI does **not** show "Unable to load Administration".
8. Optional: open Roles / Users / Categories tabs still switch.

## Pass / fail criteria
- **Pass:** Administration loads; workflow section visible; no RouteErrorBoundary error chrome.
- **Fail:** Page shows Unable to load Administration, `route-error`, or console TypeError on map.

## Out of scope
- Full workflow create/edit/delete end-to-end design correctness (unless load still fails after edit).
- Developer catalog SY-04 workflows browse (shares parse helper; already covered by unit tests).

## Evidence already collected by agent
- Vitest: `WorkflowSection.test.tsx` + `workflowsApi.test.ts` — 16 passed (wrapper/empty/array/unknown).
- `cd WebUI && ../mvnw.cmd clean install` — BUILD SUCCESS.
- Playwright surface (H2 QA, hot-copied modern assets):
  - `tests/bugs/bug-2959-admin-workflow-section.spec.js` — 2 passed
  - Asserts `perc-workflow-section` visible and `route-error` count 0

> Co-Authored by Grok Build using grok-4.5 with agent main.

**Comment by vijaya-boddipudi** [comment]
## QA result: **PASS**

Manual validation of [#2974](https://github.com/intersoftdatalabs-in/percussioncms/issues/2974) (parent [#2959](https://github.com/intersoftdatalabs-in/percussioncms/issues/2959) / PR [#2973](https://github.com/intersoftdatalabs-in/percussioncms/pull/2973)) against the issue test plan and pass/fail criteria.

| Field | Value |
| --- | --- |
| Date | 2026-08-17 |
| Environment | Local CMS `http://localhost:9992` |
| Role | **Admin** |
| Entry | Login → Home → Admin; also `?view=workflow` → `/cm/app/admin/workflow`; Explorer `http://localhost:9992/cm/app/explorer` |
| Screenshots | `tmp/qa-17-08/2974/` (local workspace) |

### Test plan

| Step | Result |
| --- | --- |
| 1. CMS running with current WebUI | Pass — app served at `:9992` |
| 2. Log in as Admin | Pass — signed in as Admin |
| 3. Open Admin (top nav) | Pass — `perc-admin-shell` / Admin tools at `/cm/app/admin` |
| 4. Administration / Workflow | Pass — Workflow is an in-shell tab (no sibling Administration shell). Clicked **Workflow**; deep link `/cm/app/admin/workflow` also loads the same tab (`aria-selected=true`) |
| 5. `perc-workflow-section` renders | Pass — `data-testid="perc-workflow-section"` present. `perc-workflow-admin-shell` is **absent** (unified Admin shell after #3088 / #3340; expected) |
| 6. Workflow table + Create | Pass — table shows **Default Workflow**; **Add new workflow** (`create-workflow-button`) visible |
| 7. No `e.map is not a function` / no “Unable to load Administration” | Pass — `route-error` count 0; no Unable to load Admin/Administration chrome; console collector had **zero** `map is not a function` errors |
| 8. Optional Roles / Users / Categories switch | Pass (tabs switch). Roles and Users loaded. Categories tab **did switch** and `perc-categories-section` mounted, but the panel showed **“An error occurred while processing your request.”** (hierarchy tree still visible). Out of scope for this issue’s pass/fail; not RouteErrorBoundary / map TypeError |

### Pass / fail criteria

- **Pass:** Administration (Admin tools) loads; workflow section visible; no RouteErrorBoundary error chrome.
- **Fail not observed:** no “Unable to load Administration”, no `route-error`, no console TypeError on `.map`.

**Verdict: PASS** for #2974 / #2959 workflow-section unwrap.

### Screenshots (local)

- `00-login-admin.png`
- `01-admin-logged-in-home.png` / `02-admin-tools-shell.png` — Admin tools (Scheduled Tasks default)
- `03-admin-workflow-section.png` — Workflows table + Add new workflow
- `04-admin-roles-tab.png` — Roles tab
- `05-admin-users-tab.png` — Users tab
- `06-admin-categories-tab.png` — Categories tab (optional; processing error noted)
- `07-admin-workflow-deep-link.png` — `/cm/app/admin/workflow`
- `08-explorer-after-login.png` — Explorer after login
