### ISSUE TITLE
QA (#2903): Developer designGaps structured code+message render

### ISSUE THREAD

**Issue by natechadwick-intsof** [intersoftdatalabs-in/percussioncms#2908]
## Parent

Parent: #2903

Parent epic: #1690

PR: https://github.com/intersoftdatalabs-in/percussioncms/pull/2907

base_branch: main

## What to verify

Developer SPA design-gap rendering after REST-GAPS-01 structured `{ code, message }` wire change on Content Type, Template, and Slot detail.

## Test plan

1. Deploy or run CMS with PR #2907 (or QA H2 docker stack after merge).

2. Log in as Admin.

3. Open **Developer → Content Types** → open any content type detail.

4. Confirm the **design gaps** section lists human-readable messages (not raw JSON / `[object Object]`).

5. Optionally inspect network response for `GET .../contenttypes/{id}`: `designGaps` is array of `{code,message}` objects.

6. Repeat for **Templates** detail and **Slots** detail (gaps section present with readable text).

7. Confirm list/detail still load without console/API errors.

## Pass / fail criteria

- **Pass:** All three detail panels show readable gap messages; JSON is structured objects on those paths.

- **Fail:** Gaps blank, show `[object Object]`, or detail page errors after the PR.

## Out of scope

- Migrating other Developer peers still on string[] designGaps

- Full design-session lock/save REST (content-type-api-gaps)

- i18n of gap codes across locales

## Evidence already collected by agent

- rest standalone `mvnw clean install`: BUILD SUCCESS, Tests run: 281

- sitemanage standalone clean install: BUILD SUCCESS; DesignGapsStructuredTest 4 tests

- WebUI clean install BUILD SUCCESS; Vitest designGaps helpers + ContentTypeDetailPanel structured render

- Product docs: `product-docs/8.2/developer/rest.md`

> Co-Authored by Grok Build using grok-4.5 with agent main.

## Agent progress (night-issue-prs)

| Slice | Issue | Status | PR | Notes | Updated |

|-------|-------|--------|----|-------|---------|

| Parent QA (do not implement qa-task) | #2908 | residual_filed | | Human FAIL: Slot detail .map crash / Unable to load Developer. Leave open for human retest. | 2026-08-18 |

| Implement residual: Slot list normalize | #3554 | pr_opened | https://github.com/intersoftdatalabs-in/percussioncms/pull/3556 | WebUI normalize associations/designGaps/finderArguments; Playwright pass | 2026-08-18 |

| Content Type detail list arrays | #3712 | pr_opened | https://github.com/intersoftdatalabs-in/percussioncms/pull/3731 | Jackson list normalize + Playwright pass | 2026-08-22 |

**Comment by natechadwick-intsof** [comment]
## Implement residual opened (QA Failed → agent queue)

Human QA remains **Failed** (Slot detail `.map is not a function` crashes Developer shell).

| | |
|--|--|
| **Implement issue** | #3554 (p2, copied from #2903) |
| **Link** | https://github.com/intersoftdatalabs-in/percussioncms/issues/3554 |
| **Assignees** | none (night-issue-prs can pick up) |
| **Not a `qa task`** | implement bind/normalize + C5 evidence |

Do not assign this qa-task to agents. Leave open for human retest after #3554.

> Co-Authored by Grok Build 1.0.4 using grok-4.6 with agent night-issue-prs-triage.

**Comment by natechadwick-intsof** [comment]
Implement residual #3554 opened PR https://github.com/intersoftdatalabs-in/percussioncms/pull/3556 for the Slot detail `.map` / non-array Jackson crash that failed this QA.

Developer → Slots (FastForward All Press Releases / Auto Index / Calendar Events) should stay mounted with readable `{code,message}` gaps. Please retest after the PR is on a QA build.


> Co-Authored by Grok Build 1.0.4 using grok-4.6 with agent night-issue-prs.

**Comment by natechadwick-intsof** [comment]
**Reconcile close (QA: Failed):** the only remaining fail steps were Slot detail .map crash (steps 6b/7). Residual #3554 is closed; implement landed in https://github.com/intersoftdatalabs-in/percussioncms/pull/3556 (merged). Structured designGaps already passed on Content Type / Template / surviving Slot rows. Unassigned; residual merged and fail steps are no longer open implement work (C5/C7).

> Co-Authored by Grok Build 1.0.5 using grok-4.6 with agent night-issue-prs-reconcile.

**Comment by natechadwick-intsof** [comment]
**Reconcile close (C5/C7):** Unassigned QA: Failed — Slot/Content Type `.map` crashes are merged.

- Fail steps 6b/7 (Slot detail `.map is not a function`): residual **#3554** / merged PR **#3556**
- Content Type detail leftover REST-GAPS-01: **#3712** / merged PR **#3731**
- Structured `{code,message}` designGaps already passed on surviving CT/Template/Slot rows
- No OPEN covering PR or remaining implementable fail steps (C7)

> Co-Authored by Grok Build 1.0.5 using grok-4.6 with agent night-issue-prs-reconcile.
